apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: "2021-09-14T06:18:33Z"
  generation: 1
  name: appstore-web-asoapi-svc
  namespace: appstore-tenant-appstore
  resourceVersion: "819516661"
  selfLink: /apis/policy/v1beta1/namespaces/appstore-tenant-appstore/poddisruptionbudgets/appstore-web-asoapi-svc
  uid: 9678d854-1523-11ec-8e71-06780865b9d4
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      deployment.harmonycloud.cn/selector: appstore-web-asoapi-svc
status:
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
