apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: "2021-11-17T06:51:07Z"
  generation: 1
  name: basicservice-opsm-svc
  namespace: basics-tenant-basicservice
  resourceVersion: "824083133"
  selfLink: /apis/policy/v1beta1/namespaces/basics-tenant-basicservice/poddisruptionbudgets/basicservice-opsm-svc
  uid: bd667feb-4772-11ec-a797-0a86de9de728
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      deployment.harmonycloud.cn/selector: basicservice-opsm-svc
status:
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
