apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: "2023-02-22T08:33:39Z"
  generation: 1
  name: hiupgrade-juapi-ops-svc
  namespace: basics-tenant-hiupgrade
  resourceVersion: "883004963"
  selfLink: /apis/policy/v1beta1/namespaces/basics-tenant-hiupgrade/poddisruptionbudgets/hiupgrade-juapi-ops-svc
  uid: 9b3fcb99-b28b-11ed-84c8-0a86de9de728
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      deployment.harmonycloud.cn/selector: hiupgrade-juapi-ops-svc
status:
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
