apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"policy/v1beta1","kind":"PodDisruptionBudget","metadata":{"annotations":{},"name":"message-messageops-svc","namespace":"basics-tenant-message"},"spec":{"maxUnavailable":1,"selector":{"matchLabels":{"deployment.harmonycloud.cn/selector":"message-messageops-svc"}}}}
  creationTimestamp: "2021-03-11T03:35:02Z"
  generation: 1
  name: message-messageops-svc
  namespace: basics-tenant-message
  resourceVersion: "527392789"
  selfLink: /apis/policy/v1beta1/namespaces/basics-tenant-message/poddisruptionbudgets/message-messageops-svc
  uid: c37ab61c-821a-11eb-a797-0a86de9de728
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      deployment.harmonycloud.cn/selector: message-messageops-svc
status:
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
