apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"policy/v1beta1","kind":"PodDisruptionBudget","metadata":{"annotations":{},"name":"monitor-controller","namespace":"kube-system"},"spec":{"maxUnavailable":1,"selector":{"matchLabels":{"deployment.harmonycloud.cn/selector":"monitor-controller"}}}}
  creationTimestamp: "2021-03-11T03:35:04Z"
  generation: 1
  name: monitor-controller
  namespace: kube-system
  resourceVersion: "527161549"
  selfLink: /apis/policy/v1beta1/namespaces/kube-system/poddisruptionbudgets/monitor-controller
  uid: c4a5b286-821a-11eb-ae42-02b93e1335fa
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      deployment.harmonycloud.cn/selector: monitor-controller
status:
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
