apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"policy/v1beta1","kind":"PodDisruptionBudget","metadata":{"annotations":{},"name":"nephele-backend-svc","namespace":"kube-system"},"spec":{"maxUnavailable":1,"selector":{"matchLabels":{"deployment.harmonycloud.cn/selector":"nephele-backend-svc"}}}}
  creationTimestamp: "2021-03-11T03:35:04Z"
  generation: 1
  name: nephele-backend-svc
  namespace: kube-system
  resourceVersion: "864369724"
  selfLink: /apis/policy/v1beta1/namespaces/kube-system/poddisruptionbudgets/nephele-backend-svc
  uid: c4a7231e-821a-11eb-ae42-02b93e1335fa
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      deployment.harmonycloud.cn/selector: nephele-backend-svc
status:
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
