apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: "2022-04-12T02:59:47Z"
  generation: 1
  name: njbp-mam-assetferry-op-svc
  namespace: superapp-tenant-njbp-mam
  resourceVersion: "917681893"
  selfLink: /apis/policy/v1beta1/namespaces/superapp-tenant-njbp-mam/poddisruptionbudgets/njbp-mam-assetferry-op-svc
  uid: 9c953d0e-ba0c-11ec-ae42-02b93e1335fa
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      deployment.harmonycloud.cn/selector: njbp-mam-assetferry-op-svc
status:
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
