apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: "2022-04-12T07:00:00Z"
  generation: 1
  name: njbp-mam-airflow-flower-svc
  namespace: superapp-tenant-njbp-mam
  resourceVersion: "650862250"
  selfLink: /apis/policy/v1beta1/namespaces/superapp-tenant-njbp-mam/poddisruptionbudgets/njbp-mam-airflow-flower-svc
  uid: 2bddc6a3-ba2e-11ec-8e71-06780865b9d4
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      deployment.harmonycloud.cn/selector: njbp-mam-airflow-flower-svc
status:
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
