apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: "2022-07-04T08:49:24Z"
  generation: 1
  name: njbp-api-analysisdatacrawler-svc
  namespace: superapp-tenant-njbp-api
  resourceVersion: "688609030"
  selfLink: /apis/policy/v1beta1/namespaces/superapp-tenant-njbp-api/poddisruptionbudgets/njbp-api-analysisdatacrawler-svc
  uid: 3435f4e5-fb76-11ec-a797-0a86de9de728
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      deployment.harmonycloud.cn/selector: njbp-api-analysisdatacrawler-svc
status:
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
