apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"policy/v1beta1","kind":"PodDisruptionBudget","metadata":{"annotations":{},"name":"nodescaling","namespace":"yunti-tenant-hybridge-pj"},"spec":{"maxUnavailable":1,"selector":{"matchLabels":{"deployment.harmonycloud.cn/selector":"nodescaling"}}}}
  creationTimestamp: "2021-03-11T03:35:06Z"
  generation: 1
  name: nodescaling
  namespace: yunti-tenant-hybridge-pj
  resourceVersion: "666368928"
  selfLink: /apis/policy/v1beta1/namespaces/yunti-tenant-hybridge-pj/poddisruptionbudgets/nodescaling
  uid: c5c84391-821a-11eb-ae42-02b93e1335fa
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      deployment.harmonycloud.cn/selector: nodescaling
status:
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
