apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"policy/v1beta1","kind":"PodDisruptionBudget","metadata":{"annotations":{},"name":"oma-websignin-svc","namespace":"mobile-tenant-oma"},"spec":{"maxUnavailable":1,"selector":{"matchLabels":{"deployment.harmonycloud.cn/selector":"oma-websignin-svc"}}}}
  creationTimestamp: "2021-03-11T03:35:04Z"
  generation: 1
  name: oma-websignin-svc
  namespace: mobile-tenant-oma
  resourceVersion: "864361508"
  selfLink: /apis/policy/v1beta1/namespaces/mobile-tenant-oma/poddisruptionbudgets/oma-websignin-svc
  uid: c4cb090f-821a-11eb-8e71-06780865b9d4
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      deployment.harmonycloud.cn/selector: oma-websignin-svc
status:
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
