apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"policy/v1beta1","kind":"PodDisruptionBudget","metadata":{"annotations":{},"name":"upstream-watcher","namespace":"kube-system"},"spec":{"maxUnavailable":1,"selector":{"matchLabels":{"deployment.harmonycloud.cn/selector":"upstream-watcher"}}}}
  creationTimestamp: "2021-03-11T03:35:04Z"
  generation: 1
  name: upstream-watcher
  namespace: kube-system
  resourceVersion: "666368841"
  selfLink: /apis/policy/v1beta1/namespaces/kube-system/poddisruptionbudgets/upstream-watcher
  uid: c4ab5419-821a-11eb-ae42-02b93e1335fa
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      deployment.harmonycloud.cn/selector: upstream-watcher
status:
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
