apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: "2022-11-16T01:47:59Z"
  generation: 1
  name: vidaa-canary-platform-svc
  namespace: vidaavoice-tenant-vidaa-canary
  resourceVersion: "757988902"
  selfLink: /apis/policy/v1beta1/namespaces/vidaavoice-tenant-vidaa-canary/poddisruptionbudgets/vidaa-canary-platform-svc
  uid: b33548df-6550-11ed-957a-06780865b9d4
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      deployment.harmonycloud.cn/selector: vidaa-canary-platform-svc
status:
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
