apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: "2023-03-20T12:01:04Z"
  generation: 1
  name: vidaa-log-nginx-svc
  namespace: vidaavoice-tenant-vidaa-log
  resourceVersion: "730150217"
  selfLink: /apis/policy/v1beta1/namespaces/vidaavoice-tenant-vidaa-log/poddisruptionbudgets/vidaa-log-nginx-svc
  uid: e3eb4dc9-c716-11ed-84c8-0a86de9de728
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      deployment.harmonycloud.cn/selector: vidaa-log-nginx-svc
status:
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
