apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
data: 
  redis.conf: |
    # User-supplied common configuration:
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly yes
    # Disable RDB persistence, AOF persistence already enabled.
    save ""
    loglevel debug
    # End of common configuration

  