apiVersion: v1
kind: PersistentVolume
metadata:
  name: redispv4
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: localdisk
  hostPath:
    path: /mnt
