apiVersion: v1
kind: Pod
metadata:
     name: busybox2
spec:
     containers:
     - name: busybox2
       image: busybox
       command: ['sh','-c','echo "configmap: $ENVVAR secret: $SECRETVAR"', 'sleep 3600']
       env: 
        - name: ENVVAR
          valueFrom:
           configMapKeyRef:
            name: my-configmap
            key: key2
        - name: SECRETVAR
          valueFrom:
           secretKeyRef:
            name: my-secret
            key: secret
      
     
