--- 
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: install git & httpd
      yum:
        name: git
        state: present
        name: httpd
        state: present

    - name: Enable httpd service
      service: 
       name: httpd
       state: started
       enabled: yes
