apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd
  name: eks-developers
rules:
  - apiGroups:
    - ""
    - argoproj.io
    resources:
    - pods
    - pods/log
    - pods/status
    - pods/exec
    - secrets
    - configmaps
    - podtemplates
    - applications
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
    - deletecollection
  - apiGroups:
    - apps
    - argoproj.io
    resources:
    - replicasets
    - applications
    - deployments
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
    - deletecollection


  # <property>
  #   <name>yarn.nodemanager.localizer.cache.cleanup.interval-ms</name>
  #   <value>300000</value>
  # </property>

  # <property>
  #   <name>yarn.nodemanager.localizer.cache.target-size-mb</name>
  #   <value>4120</value>
  # </property>