apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vidaa-internal
  name: eks-developers
rules:
  - apiGroups:
    - ""
    - argoproj.io
    resources:
    - pods
    - pods/log
    - pods/status
    - pods/exec
    - secrets
    - configmaps
    - podtemplates
    - applications
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
    - deletecollection
  - apiGroups:
    - apps
    - argoproj.io
    resources:
    - replicasets
    - applications
    - deployments
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
    - deletecollection