apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appcenter-prod
  namespace: devx
  annotations: 
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: appcenter.vidaaportal.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: appcenter-prod-service
                port:
                  name: ac-prod-port
                  # number: 80
                  
