apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo3
  namespace: monitor
spec:
  ingressClassName: kong
  rules:
    - host: "prometheus.vidaa-pg.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: prometheus-operated
                port:
                  name: http-web
