apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manage-proto-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:vidaatest/manage-proto-src
    targetRevision: HEAD
    path: api/manifest/
  destination: 
    server: https://kubernetes.default.svc
    namespace: vidaa-internal

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true



  policy.default: role:readonly
  policy.csv: |
    p, dominik, applications, *, */*, allow
    p, dominik, clusters, get, *, allow