apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, user:dominik, applications, *, */*, allow
    p, user:dominik, clusters, get, *, allow
    p, user:dominik, projects, get, *, allow
    p, user:dominik, applicationsets, get, *, allow
    