apiVersion: v1
kind: Pod
metadata:
     name: busybox2
spec:
     containers:
     - name: busybox1
       image: busybox:1.28.4
       command: ['sh','-c','while true; do sleep 3600; done']
       volumeMounts:
       - name: configmap-volume
         mountPath: /etc/config/configmap1
       - name: secret-volume
         mountPath: /etc/config/secret1
     volumes:
     - name: configmap-volume
       hostPath:
        path: /yahav2
     - name: secret-volume
       hostPath:
        path: /yahav3





       #       configMap:
       # name: my-configmap
       # - name: secret-volume
       #secret:
       # secretName: my-secret
