apiVersion: v1
kind: Pod
metadata: 
 name: liveness-probes
spec:
 containers:
 - name: liveness-probes
   image: busybox
   command: ['sh','-c','while true;do sleep 3600; done']
   livenessProbe:
    exec:
     command: ['echo','Hello World']
    initialDelaySeconds: 5     # waits 5 second from the moment he finishd to startup before we echo this command.
    periodSeconds: 5           # every 5 seconds we gnna run this command
