FROM ubuntu:bionic

ENV NGINX_VERSION 1.14.0-0ubuntu1.7

RUN apt-get update && apt-get install -y curl 
RUN apt-get update && apt-get install -y nginx=$NGINX_VERSION 

WORKDIR /var/www/html
COPY index.html ./
#ADD index.html ./

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

# sigterm stops the container 
STOPSIGNAL SIGTERM
HEALTHCHECK CMD curl localhost:80

