apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: monitoring
    prometheus-operator-validated: "true"
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 49.0.0
    chart: kube-prometheus-stack-49.0.0
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-stack-kafka.rules
  namespace: monitoring
spec:
  groups:
  - name: kafka-critical
    rules:
      - alert: KafkaConsumerGroupLagHigh
        expr: abs(kafka_consumergroup_lag_sum) > 10000
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High lag in Kafka consumer groups (instance {{ $labels.consumergroup }})"
          description: "Consumer group lag is over 10k for 5 minutes (current value: {{ $value }})."

      - alert: KafkaBrokerDown
        expr: up{job="kafka_exporter"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Kafka Broker is down (instance {{ $labels.instance }})"
          description: "A Kafka broker has been down for more than 1 minute."

      - alert: KafkaUnderReplicatedPartitions
        expr: kafka_topic_partition_under_replicated_partition > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Topic {{ $labels.topic }}: Kafka under replicated partitions (instance {{ $labels.instance }})"
          description: "There are under replicated partitions for 5 minutes (current value: {{ $value }})."

      - alert: KafkaOfflinePartitionsCount
        expr: kafka_topic_partition_leader_is_preferred{job="kafka_exporter"} == 0 and kafka_topic_partition_leader{job="kafka_exporter"} > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Topic {{ $labels.topic }}: Kafka has offline partitions (instance {{ $labels.instance }})"
          description: "There are offline partitions detected for 5 minutes (current value: {{ $value }})."