name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  tflint:
    name: Terraform validate ${{ matrix.terraform_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform_version:
          - latest
          - 0.14.0
          - 0.13.0
    steps:
      - uses: actions/checkout@master
      - name: Terraform validate
        run: tests/sanity/terraform_tests.sh
        env:
          terraform_version: "${{ matrix.terraform_version }}"

  pythontest:
    name: ${{ matrix.config.toxenv }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - toxenv: py35
            python-version: 3.5
          - toxenv: py36
            python-version: 3.6
          - toxenv: py37
            python-version: 3.7
          - toxenv: py38
            python-version: 3.8
          - toxenv: flake8
            python-version: 3.7
          - toxenv: pylint
            python-version: 3.7
          - toxenv: black
            python-version: 3.7
          - toxenv: mypy
            python-version: 3.7
          - toxenv: pytest
            python-version: 3.7

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.python-version }}

      - name: Install dependencies
        run: python -m pip install tox==3.20.0

      - name: Python test
        run: tox
        env:
          TOXENV: "${{ matrix.config.toxenv }}"
