---

 - name: Installing package
   hosts: webservers
   become: true
   tasks:
   - name: installing backup package to webservers group
     apt: name=linuxacademy_backup_package state=present
     ignore_errors: true 

 - name: Check and Create
   hosts: webservers
   become: true
   tasks:
   - name: check for archive.tar and if not exists create one!
     command: ls -l /root/archive.tar
     register: check_result
     ignore_errors: true
   - name: creating .tar file
     file:
      path: /root/archive.tar
      state: touch
     when: check_result is failed
