---
 - hosts: loadbalancer
   become: true
   tasks:
   - name: instaliing apache2
     apt: name=apache2 state=present
   - name: enable apache2
     service: name=apache2 state=started enabled=yes

 
 - hosts: webservers
   become: true
   tasks:
   - name: instaliing php and apache2
     apt:
      name: 
      - apache2
      - php
      state: present
   - name: enable apache2
     service: name=apache2 state=started enabled=yes

