---
- hosts: "k8s-master, k8s-workers"
  become: true
  gather_facts: yes
  connection: ssh

  tasks:
  - name: make sure swap is off
    become: true
    command: swapoff -a
 
  - name: remove swap from /etc/fstab
    become: true
    lineinfile:
     dest: /etc/fstab
     regexp: swap
     state: absent

  - name: installing prerequisites
    become: true
    command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - name: install repo of docker
    become: true
    command: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
                                      $(lsb_release -cs \
                                      stable"

  
