---
 - hosts: loadbalancer
   become: true
   tasks:
   - name: configure load balancer 
     template: 
      src: ../config/lb-config.j2
      dest: /etc/httpd/conf.d/lb.conf
      owner: bin
      group: wheel
      mode: 064
  
   - name: restart httpd
     service: name=httpd state=restarted
  
