---
 - hosts: webservers
   become: true
   tasks: 
   - name: upload index.php file to my app 
     copy:
       src: ../index.php
       dest: /var/www/html
       mode: 0755
   
   - name: changing php.ini file 
     lineinfile:
      path: /etc/php/7.2/apache2/php.ini
      regexp: ^short_open_tag
      line: 'short_open_tag=Off'
     notify: restart apache
    
   handlers:
     - name: restart apache
       service: name=apache2 state=restarted
