apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: uloe-mongodb
spec:
  containers:
    - name: myapp
      image: yahav876/uloe-server:0.0.2
      ports:
        - name: web
          containerPort: 3001
          protocol: TCP
      env:
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: uloe-config
              key: mongodb.host
        - name: MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: uloe-config
              key: mongodb.port
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: uloe-secure-config
              key: mongodb.username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: uloe-secure-config
              key: mongodb.password
