apiVersion: v1
kind: Service
metadata:
  name: pirate-svc
  namespace: default
spec:
  ports:
  - nodePort: 30080
    port: 30080
    protocol: TCP
    targetPort: 5000
  selector:
    app: pirate-day
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}